### PR TITLE
Css variables inconsistency

### PR DESCRIPTION
**Pull request by christopherGdynia**
Hello,

as mentioned in #738 there are some inconsistensies with the css variables, I added the css of the first components, this will make it easier to create a custom theme or dark mode.

### CODE REVIEW

**Comment by acstll** [comment]
@christopherGdynia gonna check with the colleagues before merging, but this looks good to me already! Thank you very much!

**Comment by acstll** [comment]
@christopherGdynia could you please run `yarn format` inside `packages/components` to fix the prettier check? 🙏 then we can merge :)

**Comment by christopherGdynia** [comment]
@acstll do you have a setup guide for yarn and the project? 
I am trying to get it done with npm

**Comment by acstll** [comment]
> @acstll do you have a setup guide for yarn and the project? I am trying to get it done with npm

oh, sorry I missed your message yesterday. I see you already did it, npm should work more or less the same (`npm run format`). But I see prettier "prettified" some files that didn't have to do with the PR, this is annoying.

I'm not sure why this happens (different versions of `prettier` maybe?) but I'm not sure how to fix it now.

Could you please revert the `style fix` commit (6d56ce24ff7ad64510eb068f539aee6671ce331e)? I think you do `git revert 6d56ce24ff7ad64510eb068f539aee6671ce331e`. And then we can merge it despite the original failing check.

Sorry about this 🙏 and thank you!

**Pull request merged**
