### PR TITLE
checkbox and switch css fixes for high contrast mode

### PR DESCRIPTION
**Pull request by tshimber**
Fixes https://github.com/telekom/scale/issues/2300

### CODE REVIEW

**Comment by tshimber** [comment]
@maomaoZH @acstll @felix-ico 
hi, guys! I'm new here, gonna try to make some fixes. I was suggested to mention you for review and to give detailed description.

This is a fix of https://github.com/telekom/scale/issues/2300. The reason why check-icon was disappearing were scale-switch styles. In switch component shadow is put to false, I guess there were some reason? 
image

Anyway I don't touch it, but just add extra selector in css (see changes).

Also within whis PR I've fixed disappearing borders for checkbox in high contrast mode, 'cause box-shadow borders are not visible in HC. So I just put extra blocks of css for HC mode with normal borders. Design for disabled end error checkboxes should be discussed and implemented extra, but functionally they are ok now.

Also I've added checkbox template to html folder, I hope it's ok. 

I'm wainitg for your feedback! Have a nice weekend)

**Review by maomaoZH — APPROVED** [review]
@tshimber Thanks for the PR. LGTM.  Yeah, the switch along with other input type is set shadow dom off by purpose so that the developers can access the elements easily.

**Comment by tshimber** [comment]
> @tshimber Thanks for the PR. LGTM. Yeah, the switch along with other input type is set shadow dom off by purpose so that the developers can access the elements easily.

thank you!

**Comment by tshimber** [comment]
@maomaoZH @acstll @felix-ico 
hi, guys! could you please tell, what are next steps by PRs? seems that it should be approved by all reviewers, correct? should i do smth from my side?
my team is asking me to clarify:)

**Pull request merged**
