### PR TITLE
fix(tooltip): a few issues

### PR DESCRIPTION
**Pull request by acstll**
- [x] use trigger element (child inside slot) for events, and not the host itself, to avoid margins triggering the tooltip
- [x] warn if used without a trigger element (just text, wrong usage)
- [x] add beta notice
- [x] fix jump when visible early (the element was visible before it was positioned)
- [x] use `pointer-events: none` when hidden, to avoid interfering
- [x] rename `open` to `opened` for consistency with other components (Modal et al) — ⚠️ breaking

@nowseemee if you're so kind 👀 — @marvinLaubenstein please also take a look if you have time 🙏

### CODE REVIEW

**Review by marvinLaubenstein — COMMENTED** [review]
> Really nice 🙂, but shouldn't the prop renaming from `open` to `opened` also be in the storybook ?

nice catch 🙌 — I completely forgot

**Review by nowseemee — APPROVED** [review]
thanks for adding these! 🙌🏻

**Comment by acstll** [comment]
I need yer help @nowseemee 🤠

image

**Comment by nowseemee** [comment]
> I need yer help @nowseemee 🤠
> 
> image

on it 🤠

**Pull request merged**
