### PR TITLE
test(visual): dry things up + better local reports

### PR DESCRIPTION
**Pull request by nowseemee**
@felix-ico can you have a look, please? I've removed some repetition from our visual test suites, tweaked the build script to run faster, and added `jest-html-reporter` to visualize test failures locally.

### CODE REVIEW

**Comment by felix-ico** [comment]
hi @nowseemee the code changes look good to me but when i run the tests locally get some tests that fail or time out. Am i supposed to do something different than before?

**Comment by nowseemee** [comment]
Hi @felix-ico , thanks for the review. Which tests? Is it better with the current main branch?

**Comment by felix-ico** [comment]
It's inconsistent but I'm getting a lot of failures
Screenshot 2022-08-25 at 15 45 20

Also when i check the generated html report the image links seems broken 

Screenshot 2022-08-25 at 15 44 08

Tried running on main too, and I am getting a lot of errors too, so I'm not sure now if it is a problem with my machine or docker set up.  In the past I've found that I get a lot better results with the --runInBand flag, I could try to run them again like that

**Comment by felix-ico** [comment]
ok when i use the --runInBand flag locally only 2 tests fail (and it's one of those weird sub 0.1% difference in snapshots) so it seems all good.

**Review by felix-ico — APPROVED** [review]

**Pull request merged**
