### PR TITLE
chore: replace deprecated `dist-custom-elements-bundle` dist

### PR DESCRIPTION
**Pull request by acstll**
…with the new [`dist-custom-elements`](https://stenciljs.com/docs/custom-elements#distributing-custom-elements).

This dist allows bypassing Stencil's lazy loading, and import only a specific set of components programatically (no magic), e.g.

```js
import { defineCustomElementScaleButton } from '@telekom/scale-components'

defineCustomElementScaleButton() // only `<scale-button>` is loaded
```

See https://github.com/telekom/scale/issues/1167

### CODE REVIEW

**Comment by acstll** [comment]
@nowseemee and @maomaoZH please take a look if you're so kind 🙂

**Comment by nowseemee** [comment]
when building the components I get a warning, is this fine? 
image

**Comment by nowseemee** [comment]
`yarn workspace @telekom/scale-components-angular build` command fails:
image

**Comment by nowseemee** [comment]
Vue and React proxy builds are also failing 💣

**Comment by acstll** [comment]
@nowseemee thanks a lot for testing this!

The warning is fine. The [docs explicitly say](https://stenciljs.com/docs/custom-elements#distributing-custom-elements) you can choose what output to configure as `"module"`. It'd be nice to silent it thou.

image

Also currently we get the same-but-different warning, haha.

image

As for the proxy packages failing, I will take a look into that! 🧐

**Comment by maomaoZH** [comment]
LGTM! Tested and it works great.

**Comment by maomaoZH** [comment]
Thanks a lot for the PR 👍

**Comment by acstll** [comment]
Amazing @maomaoZH, thanks a lot for the feedback. I'm glad it's working! — I still need to fix the issues with the builds of the wrapper packages failing (will do that after the next release, or right before if time allows)

**Comment by acstll** [comment]
This is finally working now, proxy packages build (found out —assuming— the code generating the proxy packages is looking for types based on the `types` key in package.json, [I had messed that up](https://github.com/telekom/scale/blob/469c5ef47c7d1915fc67641e065ddc918a0ec52a/packages/components/package.json#L16) for some reason on the first try).

@nowseemee, @maomaoZH please give me a final 👍 and I'll merge 🙏

**Comment by maomaoZH** [comment]
looks great! Thanks for the fix @acstll !

**Comment by acstll** [comment]
I will add some documentation regarding this in another PR! Thanks @maomaoZH

**Pull request merged**
