### PR TITLE
#2313 data grid sort order

### LINKED ISSUE #2313: DataGrid loses sort on data change
**Scale Version**
3.0.0-beta.151

**Framework and version**
Are you using web components in a specific framework (react, angular, vue)? If so what version of the framework? Are you using one of the auto-generated scale wrapper packages? 
React and @telekom/scale-components-react version 3.0.0-beta.151

**Current Behavior**
Upon a data update the data table loses any sort order, this can be seen in the docs with the show more example.

**Expected Behavior**
If I have sorted the table by a specific column the data should stay sorted in this order even on a data update

**Code Reproduction**
Here you can sort the data grid on the letter and then add a new letter which triggers the reset:

https://codesandbox.io/p/sandbox/scale-components-react18-with-wrapper-forked-mkd8z8

The problem can also be replicated in the https://telekom.github.io/scale/?path=/docs/components-data-grid--show-more demo by sorting by name and then clicking the show more option.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Edge and FF Developer tested
 - Version: 124.0.6367.119, 124.0.2478.80, 126.0b9

### PR DESCRIPTION
**Pull request by marcrobertscamao**
This fix only resets the sort order when the fields change, which may disable the sorting behaviour or change the field order.

If the data changes and an active sort order is set then this resorts the data accordingly.

Fixes #2313

### CODE REVIEW

**Comment by marcrobertscamao** [comment]
@acstll is there anything I can do to move this along, I am not sure why the visual tests are failing it looks like an outdated hook needs to be updated in the ci?

Also at which point are updated versions released?

**Comment by marcrobertscamao** [comment]
@maomaoZH @acstll @felix-ico is there anything happening here, we unfortunately require this feature for UAT testing

**Comment by acstll** [comment]
> I am not sure why the visual tests are failing it looks like an outdated hook needs to be updated in the ci?

correct, I think we can safely ignore them

> Also at which point are updated versions released?

currently there's no schedule but I think we can try and define one… I'll talk to @maomaoZH to get this released

**Comment by marcrobertscamao** [comment]
@acstll thank you for the quick response and resolution, let me know if there is anything else I can do to help

**Comment by acstll** [comment]
@marcrobertscamao a new version is out, I hope it helps! (We still to establish the schedule…)

**Pull request merged**
