### PR TITLE
fix: icon Buttons on Indexhtml wrong syntax

### PR DESCRIPTION
**Pull request by Lalaluka**
Tries to fix the problem I found with #382 

### Before
Bildschirmfoto 2021-06-04 um 15 34 56

### Now
Bildschirmfoto 2021-06-04 um 15 58 23

Uses the same example code as the Storybook.

### CODE REVIEW

**Review by nowseemee — APPROVED** [review]
<3

**Review by nowseemee — CHANGES_REQUESTED** [review]
oops, prettier failed - can you reformat please, @Lalaluka?

**Comment by Lalaluka** [comment]
Hi @nowseemee ,
sry for the missing format, I should have noticed that error.
But it's fixxed now.

To mitigate errors like that in the future, would it be interesting to extend the husky with a precommit function?

**Comment by nowseemee** [comment]
Hi @Lalaluka, thanks for making the build pass! I don't want to force all devs to have those hooks running before every commit or push of theirs. Here is an opt-in way to set it up on your computer: https://prettier.io/docs/en/precommit.html#option-5-shell-script

**Pull request merged**
