### PR TITLE
fix: prevent focus on first render

### PR DESCRIPTION
**Pull request by felix-ico**

### CODE REVIEW

**Comment by felix-ico** [comment]
fixes https://github.com/telekom/scale/issues/1372.

not sure if the new prop `autoFocus` should be true or false by default? If we want to keep the previous behavior (first element focussed) I should change it to `true`, if we want it to behave as the issue reporter wishes we can keep it with `false` as it is implemented here.

**Comment by felix-ico** [comment]
@acstll could you review this?

**Review by acstll — CHANGES_REQUESTED** [review]
Hey @felix-ico thanks for taking care of this one! It's working as expected now 👍 …but I think we shouldn't be exposing a `firstRender` attribute in Tab Header, it doesn't seem useful for consumers 🤔 — Could we make this something internal?

**Comment by felix-ico** [comment]
@acstll i removed the stencil prop and used a regular attribute instead, seems to work as expected.

**Review by acstll — APPROVED** [review]
👌

**Pull request merged**
