### PR TITLE
docs: add interactive icon story

### PR DESCRIPTION
**Pull request by felix-ico**

### CODE REVIEW

**Comment by nowseemee** [comment]
thanks for the PR! 🎉 Can you add visual tests, including the usual agent states, please?

**Comment by felix-ico** [comment]
Hey @nowseemee. Sure, it's not something i've done before but I think i can do that by following the readme in packages/visual-tests

**Comment by acstll** [comment]
We have the ghost variant documented in `next`, no need for a Story I think. This is no longer needed, right? @felix-ico

**Comment by felix-ico** [comment]
discussed with @acstll, can be closed

**Pull request closed without merging**
