### PR TITLE
fix(dropdown-select): ensure single dropdown open at a time

### PR DESCRIPTION
**Pull request by MihailsFX1nce**
Implement global state to track the active dropdown. Modify handleClick method to close any other open dropdown before opening the clicked one. This ensures that only one dropdown can be open at a time.

### CODE REVIEW

**Comment by MihailsFX1nce** [comment]
Fix is for https://github.com/telekom/scale/issues/2285

**Comment by MihailsFX1nce** [comment]
@maomaoZH , could you please provide more info, what should/have to be done to fix the job runner: https://github.com/telekom/scale/actions/runs/8454004700/job/23190806654?pr=2307

**Comment by felix-ico** [comment]
@MihailsFX1nce there was only a visual test job failing, but this was unrelated to your code changes and rather an issue with the visual test pipeline. All the other jobs were good, thanks for the PR!

**Comment by MihailsFX1nce** [comment]
@felix-ico , no problem! You are welcome! 🙂

**Comment by MihailsFX1nce** [comment]
@felix-ico , how much time does it take usually to update package version?

**Comment by felix-ico** [comment]
@MihailsFX1nce we don't have a schedule currently, as the scale library is not under active development anymore, releases happen ad-hoc (I will bring this up in our next daily and push for a release..)

**Comment by MihailsFX1nce** [comment]
@felix-ico , thank you for response! We will be looking for the new release.

**Pull request merged**
