### PR TITLE
fix: reset pagination to last page if new records are rendered are less than previous

### PR DESCRIPTION
**Pull request by ayeshaa-m**
reset pagination start point

### CODE REVIEW

**Review by nowseemee — APPROVED** [review]

**Review by marvinLaubenstein — APPROVED** [review]

**Comment by felix-ico** [comment]
Hi @ayeshaa-m I'm thinking if we should make this feature optional? I know that some users programmatically add rows to a data grid (for example by populating the data grid with API responses)... currently this implementation would  go back to the first page every time a new row is added to the data-grid. What do you think?

**Comment by marvinLaubenstein** [comment]
@felix-ico Good point. We should make it optional

**Comment by ayeshaa-m** [comment]
@felix-ico @acstll As discussed, the pagination is set to last page if new records are less than the previous records count.

**Review by felix-ico — APPROVED** [review]
looks good to me!

**Pull request merged**
