### PR TITLE
feat(button): forms will submit with Enter key

### LINKED ISSUE #859: Form submit not triggered on enter
In a form that contains multiple scale-text-field ans a scale-button of type submit, hitting enter in any of the inputs does not trigger the submit of the form as it should be.

### PR DESCRIPTION
**Pull request by acstll**
Fixes #859.

- Not a "React wrapper" thing
- Same problem with "generic" web component
- Forms with a single text input will be submitted with the Enter key, even without a button: https://stackoverflow.com/a/35235768

---

- [x] fix
- [x] unit or e2e test
- [ ] find a better word instead of "fallback"?

### CODE REVIEW

**Comment by nowseemee** [comment]
My five cents: I would add the [form behavior findings](https://github.com/telekom/scale/issues/859#issuecomment-1173599883) to our docs and point people to it instead of extending the button component with this.

**Review by nowseemee — APPROVED** [review]
And this code is not wrong either - not easy to decide what's the correct thing to do.

**Comment by acstll** [comment]
@nowseemee I think I'm OK with merging this. Polished it a tiny bit. Any final thoughts? 🤠

**Comment by nowseemee** [comment]
let's go 🫣

**Pull request merged**
