### PR TITLE
Data list changes

### PR DESCRIPTION
**Pull request by W1ckh3ad**
Hello there,

its @christopherGdynia,
I can't contribute to Github on my work computer.

This refers to issue #447 and PR #474

I implemented the mentioned lines in the review.

### CODE REVIEW

**Comment by W1ckh3ad** [comment]
Ups, I forgot the tests

**Comment by W1ckh3ad** [comment]
@acstll I have some troubles setting up the test

###Installing dependencies with yarn
I got an Error with my TLS cetificate, turned off strict-ssl and it worked (got a lot of warnings) and I got this error 

```
[4/4] Building fresh packages...
[1/14] ⡀ husky
[2/14] ⡀ canvas
[8/14] ⡀ puppeteer
[6/14] ⡀ deasync
error C:\Users\Christopher\source\repos\scale\node_modules\deasync: Command failed.
Exit code: 1
Command: node ./build.js
```

after that I tried to call the build script again, i got a lot of warnings again, but it worked

Were these the right steps?

**Comment by W1ckh3ad** [comment]
And it touched multiple files in the angular, react and vue package

**Comment by acstll** [comment]
@W1ckh3ad @christopherGdynia sorry for the confusion 🙏 

I should have suggested we wait a bit for the original contributor to say something. He reacted immediately to our last messages. We have a new PR, I'll work to get that one merged.

Thank you for your super quick response.

**Pull request closed without merging**
