### PR TITLE
fix(app-header): solving issue with width between 1023 and 1024 px

### PR DESCRIPTION
**Pull request by marvinLaubenstein**
Solving "Bug"-Issue:

- #1209

### CODE REVIEW

**Comment by nowseemee** [comment]
How does one set the viewport between 1023 and 1024? 🃏

**Comment by marvinLaubenstein** [comment]
By manually moving the window and then landing the width at, for example, 1023.3 🤓. With the comma pixels there are no more problems. Even if it is actually illogical to assign comma pixels

**Comment by nowseemee** [comment]
Hm, I'm not able to reproduce the original issue but with the changes in this PR I see this:
image

**Review by nowseemee — CHANGES_REQUESTED** [review]
visual tests should not show any change. Seems like there is a problem when the viewport is 1024px.

**Comment by marvinLaubenstein** [comment]
I could reproduce it again with the current main branch

Bildschirmfoto 2022-11-28 um 21 07 51

**Comment by felix-ico** [comment]
from the discussion with devs: maybe we can try to expand the media query instead of adding fractions of pixels. for example: `min-width: .... AND max-width: ...`

**Comment by felix-ico** [comment]
we're closing this, it's fixed in https://github.com/telekom/scale/pull/1650

**Pull request closed without merging**
