### PR TITLE
fix(telekom-nav-flyout): add variant prop

### LINKED ISSUE #1746: mobile menu in scale-telekom-header is not scrollable
**Scale Version**
3.0.0-beta.131

**Current Behavior**
The mobile menu in scale-telekom-header is not scrollable - it is not possible to reach items that are hidden when long navigations lists are hidden due to restricted screen height.

image

**Expected Behavior**
Scrolling should be possible inside the mobile menu to allow reaching all items in long navigation lists.

image

### PR DESCRIPTION
**Pull request by acstll**
Fixes #1746 and #1747.

### CODE REVIEW

**Comment by acstll** [comment]
@nowseemee if you're so kind… 👀 👀

**Review by nowseemee — APPROVED** [review]
this is such a nice improvement!

**Comment by acstll** [comment]
@nowseemee I also removed the need for the `burger-item` class [in here](https://github.com/telekom/scale/pull/1764/commits/dc6c38801ca82cd829d1b2a751ebea00b8c69750), with a more formal solution, although it could be still be polished a bit… let me know what you think!

**Comment by nowseemee** [comment]
it's great but it has a lot of conflicts unfortunately :(

**Comment by acstll** [comment]
> it's great but it has a lot of conflicts unfortunately :(

yes, I was expecting those conflicts, that's also why I was waiting for https://github.com/telekom/scale/pull/1738 before merging.

I'll fix those 🙏 😅

**Comment by nowseemee** [comment]
:shipit:

**Pull request merged**
